import { getAuth, GoogleAuthProvider, signInWithPopup, signOut } from 'firebase/auth';
import { collection, getFirestore } from 'firebase/firestore';
import Head from 'next/head';
import Image from 'next/image';
import { AuthProvider, FirestoreProvider, useAuth, useFirebaseApp, useFirestore, useFirestoreCollectionData, useUser } from 'reactfire';
import styles from '../styles/Home.module.css';

function UserInfo() {
  const auth = useAuth();
  const { data: user } = useUser();

  const signIn = () => signInWithPopup(auth, new GoogleAuthProvider());
  if (!user) {
    return <button onClick={signIn}>Sign in</button>;
  }

  return (
    <div>
      <div>Welcome, {user.displayName}</div>
      <img src={user.photoURL} alt={user.displayName} />
      <button onClick={() => signOut(auth)}>Log out</button>
    </div>
  );
}

function FeatureList() {
  const firestore = useFirestore();
  const featuresCollection = collection(firestore, 'features');
  const { status, data: features } = useFirestoreCollectionData(featuresCollection, {
    idField: 'id',
  });

  if (status === 'loading') {
    return <div>Loading...</div>;
  }

  return features.map((feature) => <li key={feature.id}>{feature.title}</li>);
}

export default function Home() {
  const app = useFirebaseApp();
  return (
    <AuthProvider sdk={getAuth(app)}>
      <FirestoreProvider sdk={getFirestore(app)}>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <h1 className={styles.title}>Feature Voting App!</h1>

            <UserInfo />
            <ul>
              <FeatureList />
            </ul>
          </main>

          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
              <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            </a>
          </footer>
        </div>
      </FirestoreProvider>
    </AuthProvider>
  );
}
